config/routes.rb
Rails.application.routes.draw do
  get 'developers/dashboard'
  get 'clients/dashboard'
  get '/developers/dashboard' => "developers#dashboard", :as => :developer_root
  get '/clients/dashboard' => "clients#dashboard", :as => :client_root
  get '/developers/client_details'
  devise_for :clients, controllers: { sessions: "clients/sessions", registrations: "clients/registrations" }
  devise_for :developers, controllers: { sessions: "developers/sessions", registrations: "developers/registrations" }
  
  resources :projects do
    resources :project_members
    resources :notes
    resource :conversation do 
      resources :messages
    end
  end
  root 'pages#home'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :project
  has_many :messages

  accepts_nested_attributes_for :messages
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  

 

  # GET /conversations/1 or /conversations/1.json
  def show
    @conversation = Conversation.find_by(project_id: params[:project_id])
    @messages = @conversation.messages.order(created_at: :desc)
    @project = Project.find(params[:project_id])
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations or /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conversation_params
      params.require(:conversation).permit(:project_id)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_with(model: conversation) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
        <% conversation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conversations</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.project_id %></td>
        <td><%= link_to 'Show', conversation %></td>
        <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<hr style="visibility:hidden;margin-top:1.5rem">
<div class="container text-center" id="conversation-page">
	<%= link_to "Back to Project", project_path(@conversation.project), class: 'btn btn-danger' %>
	<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newMessageModal">
	  Send a Message
	</button>
			<div class="container" id="conversation-box" style="">

				<div id="conversation-messages">

					<% if @messages.blank? %>
						<h3 style="color:orange;">No Messages in this Thread Yet!</h3>
					<% else %>
						<% @messages.each do |message| %>
							<% if message.client_id == nil %>
								<% @developer = @project.developer %>
								<div class="developer-message">
									<p><%= message.body %><br>
										<i><span style="color:black;font-size:.7rem;">Posted By: <%= @developer.first_name %> on <%= message.created_at.strftime("%m/%d/%Y") %></span></i>
									</p>
								</div>
							<% else %>
								
								<div class="client-message">
									<p><%= message.body %><br>
										<% @project.project_members.each do |pm| %>
										<% if pm.client_id == message.client_id %>
										<% @client = Client.find_by(id: pm.client) %>
										<i><span style="color:black;font-size:.7rem;">Posted By: <%= @client.first_name %> on <%= message.created_at.strftime("%m/%d/%Y") %></span></i>
										<% end %>
										<% end %>

									</p>
								</div>
								
							<% end %><br>					

						<% end %>
					<% end %>

				</div>
			</div>

		


</div>


<div class="modal fade" id="newMessageModal" tabindex="-1" aria-labelledby="newMessageModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="newMessageModalLabel">Create a Message</h5>
	        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	      </div>
	      <div class="modal-body justify-content-center text-center">

	      	<%= form_for [@project, @conversation, @conversation.messages.build] do |form| %>
			  

			  <div class="field">

			    <%= form.text_area :body, cols: "48", rows: "7", required: true %><br><br>
			  </div>

			  <div class="actions">
			    <%= form.submit "Send Message", class: 'btn btn-success' %>
			  </div>
			<% end %>

	        	
					

	      </div>
	      <div class="modal-footer">
	       
								
			
	      </div>
	    </div>
	  </div>
	</div>	