config/routes.rb
Rails.application.routes.draw do
  get 'developers/dashboard'
  get 'clients/dashboard'
  get '/developers/dashboard' => "developers#dashboard", :as => :developer_root
  get '/clients/dashboard' => "clients#dashboard", :as => :client_root
  get '/developers/client_details'
  devise_for :clients, controllers: { sessions: "clients/sessions", registrations: "clients/registrations" }
  devise_for :developers, controllers: { sessions: "developers/sessions", registrations: "developers/registrations" }
  
  resources :projects do
    resources :project_members
    resources :notes
    resource :conversation do 
      resources :messages
    end
  end
  root 'pages#home'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :developer
  has_many :project_members
  has_many :clients, :through => :project_members
  has_many :notes
  has_one :conversation

  accepts_nested_attributes_for :notes
  accepts_nested_attributes_for :conversation
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:edit, :update, :destroy]

  def show
    if current_developer
      @project = current_developer.projects.find(params[:id])
      @project_members = @project.project_members
      @notes = @project.notes.order(created_at: :desc)
    elsif current_client
      @project = Project.find(params[:id])
      @project_members = @project.project_members
      @notes = @project.notes.order(created_at: :desc)
    else
      404
    end

    respond_to do |format|
      format.html
      format.js

    end
  end

  def new
  	@project = Project.new
  end

  def edit
  end

  def create

  	@project = Project.new(project_params)
  	@project.developer_id = current_developer.id
    @project.build_conversation
  	# @project.project_members.new(developer: current_developer)

  	respond_to do |format|
  		if @project.save
        
  			format.html {redirect_to @project, notice: "Your project was successfully created!"}
  		else
  			format.html {render :new, status: :unprocessable_entity}
  		end
  	end

  end

  def update

    old_completion_date = @project.projected_completion
    old_percentage = @project.percent_complete
    old_balance = @project.balance

    respond_to do |format|
      if @project.update(project_params)
        create_update_with_change(old_completion_date, old_percentage, old_balance)
        SiteMailer.new_update(Client.find(params[:client]), current_developer).deliver_now
        format.html {redirect_to @project, notice: "Updated Successfully"}
      else
        format.html {render :edit, status: :unprocessable_entity}
      end
    end
  end

  def destroy
  end


  private

  	# Please, NOBODY touch these functions, one will cause a huge mess in app flow and the other is for security (meant to prevent attackers from injecting whatever they want into the database)

  	def set_project
  	  @project = current_developer.projects.find(params[:id])
  	end



  	def project_params
  		params.require(:project).permit(:projected_completion, :title, :description, :percent_complete, :balance, note_attributes: [:id, :developer_id, :title, :body])
  	end

    # Method to create an update when the developer modifies one of the project details (ensures that the client doesn't go unaware when critical details are changed)

    def create_update_with_change(old_completion_date, old_percentage, old_balance)
      if @project.projected_completion != old_completion_date
        @project.notes.create(project_id: @project, developer_id: current_developer.id, title: "Projected Completion Date Updated By #{current_developer.first_name}", body: "The Project's projected completion date was changed from #{old_completion_date} to #{@project.projected_completion} by #{current_developer.first_name}")
      elsif @project.percent_complete != old_percentage
        @project.notes.create(project_id: @project, developer_id: current_developer.id, title: "Project Completion Percentage Updated By #{current_developer.first_name}", body: "The Project's completion percentage was updated from #{old_percentage} percent complete to #{@project.percent_complete} percent complete by #{current_developer.first_name}")
      elsif old_balance != @project.balance
        @project.notes.create(project_id: @project, developer_id: current_developer.id, title: "Project Balance Updated By #{current_developer.first_name}", body: "The Project's Balance date was changed from #{old_balance} to #{@project.balance} by #{current_developer.first_name}")
      else

      end
    end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_client_show.html.erb
<div class="show-page-divider"><p></p></div>

<div class="container-fluid h-100" id="dev-show-page">

	<div class="row h-100">

		<div class="offset-md-1 col-md-3 text-center" id="left-show-page-column">
			<h2 class="text-center"><%=@project.title %><hr></h2>

			<h5>Developer:</h5>

			<% if @project.developer.profile_photo.url == nil %>
	          <img class="img-fluid rounded-circle" alt="50x50" height="150" width="150" src="https://wedevelop.s3-us-west-2.amazonaws.com/computer-1331579_640.png" data-holder-rendered="true">
	        <% else %>
	          <%= image_tag(@project.developer.profile_photo.client_card.url, class: 'img-fluid rounded-circle') %>
	        <% end %>
		
			<p>- <%= @project.developer.first_name %> at <%= @project.developer.company_name %><br>
				Contact: <%= @project.developer.email %><br>
				<%= link_to "Message", project_conversation_path(@project), class: 'btn btn-primary' %>
			</p>



			<h5>Projected Completion Date:</h5>
			<p><%= @project.projected_completion.strftime("%m/%d/%Y") %></p>
			<br>
			<h5>Purpose/Goal:</h5>
			<p><%= @project.description %></p>
		
			
		</div>

		<div class="offset-md-1 col-md-6 h-100">
			<div class="row" id="show-page-right-half">
				<div class="col-md-12 show-page-right-box-small">
					<div class="row h-100">
						<div class="col-md-4 h-100 d-flex justify-content-center" style="">
							<div class="progress">
							  <div class="progress-bar progress-bar-striped progress-bar-animated bg-warning" role="progressbar" style="width:<%= @project.percent_complete %>%"  aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
							  <div class="progress-bar-title text-center"><%= @project.percent_complete %>% complete</div>					  
							</div>
						</div>					
						<div class="col-md-8 text-center" style="margin:auto;">
							<h5>Remaining Balance:</h5>
							<h3><b>$<%= @project.balance %></b></h3>

							<!-- Button ready for payment implementation -->

							<!-- <p><button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#paymentModal">Make a Payment</button></p> -->
						</div>

						<div class="col-md-12 updates-section" id="">
							<div class="row">
								<h2 class="text-center">Updates</h2>
							</div>
							<hr>
							<div class="row" id="updates-table">

								<% if @notes.empty? %>
									<h3 class="text-center">Updates Will Be Listed Here As They Are Published</h3>
								<% else %>

								<table class="table" style="border-collapse:collapse;">
								  <thead>
								    <tr class="d-flex">
								      <th class="col-1" scope="col"></th>
								      <th class="col-2" scope="col">Date</th>
								      <th class="col-7" scope="col">Header</th>
								      <th class="col-2" scope="col"></th>

								    </tr>
								  </thead>
								  <tbody>
								  	<% @notes.each do |note| %>

									    <tr class="d-flex">
									      <td class="col-1" scope="row"></td>
									      <td class="col-2"><%= note.created_at.strftime("%m/%d/%Y") %></td>
									      <td class="col-7"><%= truncate(note.title, :length => 50) %></td>
									      <td class="col-2"><button type="button" class="accordian-toggle btn btn-link" data-bs-toggle="collapse" data-bs-target="#update<%= note.id %>">View Update</button></td>
									    </tr>

									    <tr>
									    	<td colspan="6" class="hiddenRow">
									    		<div id="update<%= note.id %>" class="accordion-body collapse">
									    			<p><%= note.body %></p>
									    		</div>
									    	</td>
									    </tr>
									    

									<% end %>
								    
								  </tbody>
								</table>

								<% end %>
								
							</div>
						</div>

					</div>
					
				</div>				
					

			</div>
		</div>



	</div> <!-- end of row -->

	<!-- MODAL FOR PAYMENT IMPLEMENTATION -->

	<!-- <div class="modal fade" id="paymentModal" tabindex="-1" aria-labelledby="paymentModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="paymentModalLabel">Make A Payment!</h5>
	        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	      </div>
	      <div class="modal-body justify-content-center text-center">

	      	
	        	<%= form_with(model: project) do |f| %>

	        		<div class="form-group">								
					<%= f.number_field :payment_amount %>
					</div>
					<br>
					<button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
	        		<button type="button" class="btn btn-primary">Submit</button>
					
					

	      </div>
	      <div class="modal-footer"> -->
	        
								
			<% end %>
	      </div>
	    </div>
	  </div>
	</div>

</div>

app/views/projects/_developer_show.html.erb
<div class="show-page-divider"><p></p></div>

<div class="container-fluid h-100" id="dev-show-page">

	<div class="row h-100">

		<div class="offset-md-1 col-md-3 text-center" id="left-show-page-column">
			<h3 class="text-center" style="color:black;"><b><%=@project.title %></b><hr></h3>

			<h5>Client(s):</h5>
			<% @project_members.each do |pm| %>
			<p>- <%= pm.client.first_name %> at <%= pm.client.company_name %><br>
				Contact: <%= pm.client.email %></p>

			<% end %>
			<%= link_to "Message", project_conversation_path(@project), class: 'btn btn-primary' %>
			<h5>Projected Completion Date:</h5>
			<p><%= @project.projected_completion.strftime("%m/%d/%Y") %> <br>
			<button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#updateCompletionModal">
			Update Completion Date
			</button></p>
			<h5>Purpose/Goal:</h5>
			<p><%= @project.description %></p>
			<h5>Remaining Balance:</h5>
			<h3><b>$<%= @project.balance %></b><br>
				<p><button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#updateBalanceModal">Update Balance
				</button></p>
			</h3>
		</div>

		<div class="offset-md-1 col-md-6 h-100">
			<div class="row" id="show-page-right-half">
				<div class="col-md-12 show-page-right-box-small">
					<div class="row h-100">
						<div class="col-md-4 h-100">

							<div class="progress">
							  <div class="progress-bar progress-bar-striped progress-bar-animated bg-warning" role="progressbar" style="width:<%= @project.percent_complete %>%"  aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
							  <div class="progress-bar-title text-center"><%= @project.percent_complete %>% complete</div>
							</div>

							<div class="text-center">
								<button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#updateCompletionPercentageModal">Update</button>
							</div>
						</div>

						<div class="col-md-8 text-center">
							<h5>Add a Client to your project!</h5>
		
							<%= form_for [@project, ProjectMember.new] do |new_member| %>
								
								<%= new_member.text_field :email, placeholder: "Email", required: true %>
								<%= new_member.text_field :first_name, placeholder: "First Name", required: true %>
								<%= new_member.text_field :phone, placeholder: "Phone Number", required: true %>
								<%= new_member.text_field :company_name, placeholder: "Company Name", required: true %>
								<%= new_member.number_field :rate, placeholder: "Client's Rate", required: true %>
								<%= hidden_field_tag 'developer_id', current_developer.id %>
								<%= new_member.submit "Invite Client!", class: 'btn btn-primary btn-sm' %>
								
							<% end %>

						</div>

						<div class="col-md-12 justify-content-center updates-section" id="">

							<div class="row text-center">
								<div class="col-md-12">
									<h2>Updates</h2>
									<br>
									<button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#updateFormModal">
									  Add a New Update
									</button>
								</div>

								

								
							</div>
							<hr>
							<div class="row" id="updates-table">
								<% if @notes.empty? %>
									<h3 class="text-center">Updates Will Be Listed Here As They Are Published</h3>
								<% else %>

								<table class="table" style="border-collapse:collapse;">
								  <thead>
								    <tr class="d-flex">
								      <th class="col-1" scope="col"></th>
								      <th class="col-2" scope="col">Date</th>
								      <th class="col-7" scope="col">Header</th>
								      <th class="col-2" scope="col"></th>

								    </tr>
								  </thead>
								  <tbody>
								  	<% @notes.each do |note| %>

									    <tr class="d-flex">
									      <td class="col-1" scope="row"></td>
									      <td class="col-2"><%= note.created_at.strftime("%m/%d/%Y") %></td>
									      <td class="col-7"><%= truncate(note.title, :length => 50) %></td>
									      <td class="col-2"><button type="button" class="accordian-toggle btn btn-link btn-sm" data-bs-toggle="collapse" data-bs-target="#update<%= note.id %>">View Update</button></td>
									    </tr>

									    <tr>
									    	<td colspan="6" class="hiddenRow">
									    		<div id="update<%= note.id %>" class="accordion-body collapse">
									    			<p><%= note.body %></p>
									    		</div>
									    	</td>
									    </tr>
									    

									<% end %>
								    
								  </tbody>
								</table>

								<% end %>
								
							</div>

						</div> <!-- end of updates section -->

					</div>
					
				</div>				
					

			</div>
		</div>



	</div> <!-- end of row -->

	<!-- New Update Form Modal -->
	<div class="modal fade" id="updateFormModal" tabindex="-1" aria-labelledby="updateFormModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="updateFormModalLabel">Add an Update!</h5>
	        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	      </div>
	      <div class="modal-body justify-content-center text-center">

	      	
	        	<%= form_for [@project, @project.notes.build] do |f| %>

	        		<div class="form-group">								
						<%= f.text_field :title, placeholder: "Enter a Title", size: "30", required: true %>
					</div>
					<br>
					<div class="form-group">
						<%= f.text_area :body, placeholder: "Enter your update here", cols: "30", rows: "10", required: true %>
					</div>
					<% @project_members.each do |pm| %>
						<%= hidden_field_tag :client, pm.client.id %>
					<% end %>
					
					<!-- the solution to this issue of the submit button not working until after page refresh was solved by moving this submit button into the same div as rest of form -->
					<br>
					<%= f.submit "Submit Update", class: 'btn btn-primary' %>
	      </div>
	      <div class="modal-footer">
	        
	        
								
			<% end %>
	      </div>
	    </div>
	  </div>
	</div>

	<!-- Update Projected Completion Modal -->
	<div class="modal fade" id="updateCompletionModal" tabindex="-1" aria-labelledby="updateCompletionModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="updateCompletionModalLabel">Update the Project Completion Date</h5>
	        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	      </div>
	      <div class="modal-body justify-content-center text-center">

	      	
	        	<%= form_with(model: project) do |f| %>

	        		<div class="form-group">								
					<%= f.date_select :projected_completion %>
					</div>
					<br>
					<% @project_members.each do |pm| %>
						<%= hidden_field_tag :client, pm.client.id %>
					<% end %>
					<button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
	        		<%= f.submit "Submit", class: 'btn btn-primary' %>
					
					

	      </div>
	      <div class="modal-footer">
	        
								
			<% end %>
	      </div>
	    </div>
	  </div>
	</div>


	<!-- Update Project Balance Modal -->
	<div class="modal fade" id="updateBalanceModal" tabindex="-1" aria-labelledby="updateBalanceModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="updateBalanceModalLabel">Update the Project Balance</h5>
	        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	      </div>
	      <div class="modal-body justify-content-center text-center">

	      	
	        	<%= form_with(model: project) do |f| %>

	        		<div class="form-group">								
					<%= f.number_field :balance %>
					</div>
					<br>
					<% @project_members.each do |pm| %>
						<%= hidden_field_tag :client, pm.client.id %>
					<% end %>
					<button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
	        		<%= f.submit "Submit", class: 'btn btn-primary' %>
					

	      </div>
	      <div class="modal-footer">
	       
								
			<% end %>
	      </div>
	    </div>
	  </div>
	</div>


	<!-- Update Percentage Completion Modal -->
	<div class="modal fade" id="updateCompletionPercentageModal" tabindex="-1" aria-labelledby="updateCompletionPercentageModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="updateCompletionPercentageModalLabel">Update the Project Completion Percentage</h5>
	        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	      </div>
	      <div class="modal-body justify-content-center text-center">

	      	
	        	<%= form_with(model: project) do |f| %>

	        		<div class="form-group">								
					<%= f.number_field :percent_complete %>
					</div>
					<br>
					<% @project_members.each do |pm| %>
						<%= hidden_field_tag :client, pm.client.id %>
					<% end %>
					<button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
	        		<%= f.submit "Submit", class: 'btn btn-primary' %>
					
					

	      </div>
	      <div class="modal-footer">
	        
								
			<% end %>
	      </div>
	    </div>
	  </div>
	</div>


	<!-- View Update Modal -->
	<div class="modal fade" id="updateViewModal" tabindex="-1" aria-labelledby="updateViewModalLabel" aria-hidden="true"></div>
</div>

app/views/projects/_form.html.erb
<div class="row bg-light" id="new-project-form">

	<%= form_with(model: project) do |form| %>
		<% if project.errors.any? %>
			<div id="error_explanation">
		      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

		      <ul>
		        <% project.errors.each do |error| %>
		          <li><%= error.full_message %></li>
		        <% end %>
		      </ul>
		    </div>
		<% end %>

	<div class="col-md-12">

		<div class="field">
			<h3><%= form.label :title, "Come up with a great title!" %></h3><br>
			<p><%= form.text_field :title, size: "50", required: true %></p>
		</div>

	</div>

	<div class="col-md-12">
		<div class="field">
			<h3><%= form.label :description, "Tell us a bit about the project (purpose, functionality, etc)" %></h3><br>
			<p><%= form.text_area :description, cols: "50", rows: "5", required: true %></p>
		</div>
	</div>

		<div class="field">
			<h3><%= form.label :projected_completion, "When do you expect to have this project completed by?" %></h3><br>
			<p><%= form.date_select :projected_completion %></p>
		</div>

		<div class="field">
			<h3><%= form.label :percent_complete, "How much of the project is already completed? (0-100, a brand new project would be '0')" %></h3><br>
			<p><%= form.number_field :percent_complete, required: true %></p>
		</div>

		<div class="field">
			<h3><%= form.label :balance, "Enter the quote you gave your client for this project:" %></h3><br>
			<p><%= form.number_field :balance %></p>
		</div>

		<div class="actions">
			<p><%= form.submit class: 'btn btn-success' %> or <%= link_to 'Go Back', developer_root_path, class: 'btn btn-danger' %> </p>
		</div>

	<% end %>

</div>

app/views/projects/edit.html.erb
<h1>This is the PROJECT edit page, should bring the user back to a page that looks similar to the new/create page</h1>

app/views/projects/new.html.erb
<div class="container text-center">

	<%= render 'form', project: @project %>


</div>

app/views/projects/show.html.erb
<% if current_developer %>
	<%= render 'developer_show', project: @project %>
<% elsif current_client %>
	<%= render 'client_show', project: @project %>
<% else %>
	<h1>404 error - access prohibited</h1>
<% end %>