config/routes.rb
Rails.application.routes.draw do
  get 'developers/dashboard'
  get 'clients/dashboard'
  get '/developers/dashboard' => "developers#dashboard", :as => :developer_root
  get '/clients/dashboard' => "clients#dashboard", :as => :client_root
  get '/developers/client_details'
  devise_for :clients, controllers: { sessions: "clients/sessions", registrations: "clients/registrations" }
  devise_for :developers, controllers: { sessions: "developers/sessions", registrations: "developers/registrations" }
  
  resources :projects do
    resources :project_members
    resources :notes
    resource :conversation do 
      resources :messages
    end
  end
  root 'pages#home'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :project_members
	has_many :developers, :through => :project_members
	has_many :projects, :through => :project_members

	mount_uploader :profile_photo, ProfilePhotoUploader
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :project
  has_many :messages

  accepts_nested_attributes_for :messages
end

app/models/developer.rb
class Developer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include DeviseInvitable::Inviter

	has_many :project_members
	has_many :clients, :through => :project_members
	has_many :projects

	mount_uploader :profile_photo, ProfilePhotoUploader
	
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :project
  belongs_to :developer
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :developer
  has_many :project_members
  has_many :clients, :through => :project_members
  has_many :notes
  has_one :conversation

  accepts_nested_attributes_for :notes
  accepts_nested_attributes_for :conversation
  
end

app/models/project_member.rb
class ProjectMember < ApplicationRecord
	belongs_to :project
	belongs_to :client
	belongs_to :developer

	attribute :email
	attribute :company_name
	attribute :phone
	attribute :rate
	attribute :first_name

	def assign_client
		check_for_client = Client.find_by(email: email)
		current_developer = Developer.find_by(id: developer_id)
		if !check_for_client.blank?
			SiteMailer.new_invite(check_for_client, current_developer).deliver_now
		end
		# check_for_client.blank? self.client = Client.invite!(email: email) : self.client = check_for_client
		self.client = if check_for_client.blank?
						Client.invite!(email: email, first_name: first_name, rate: rate, company_name: company_name, phone: phone)
					else
						check_for_client
					end
	end

	
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_action :authenticate_client!


  def dashboard
  	@project_members = current_client.project_members
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_action :set_message, only: %i[ show edit update destroy ]

  
  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  # def edit
  # end

  # POST /messages or /messages.json
  def create
    @project = Project.find(params[:project_id])
    @conversation = @project.conversation
    @message = @conversation.messages.new(message_params)
    if current_developer
      @message.developer_id = current_developer.id
    else
      @message.client_id = current_client.id 
    end

    
      if @message.save
        if current_client
          SiteMailer.notify_developer_new_message(current_client, @project.developer, @project).deliver_now
          redirect_to project_conversation_path, notice: "Message was successfully created." 
        else
          @project.project_members.each do |f|
            SiteMailer.notify_client_new_message(f.client, current_developer, @project).deliver_now
            
          end
          redirect_to project_conversation_path, notice: "Message was successfully created."
        end

      else
        render :new, status: :unprocessable_entity 
      end
    
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  # def update
  #   respond_to do |format|
  #     if @message.update(message_params)
  #       format.html { redirect_to @message, notice: "Message was successfully updated." }
  #       format.json { render :show, status: :ok, location: @message }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @message.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /messages/1 or /messages/1.json
  # def destroy
  #   @message.destroy
  #   respond_to do |format|
  #     format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:body, :developer_id, :client_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_developer!, only: [:create, :new]

  def show
  	
  end

  def new

  end

  def create
  	@project = current_developer.projects.find(params[:project_id])
  	@note = @project.notes.new(note_params)
  	@note.project = @project 
  	@note.developer = current_developer

  	respond_to do |format|
  		if @note.save
        SiteMailer.new_update(Client.find(params[:client]), current_developer).deliver_now
  			format.html {redirect_to @project, notice: 'Your update was created successfully!'}
  		else
  			format.html {render @project, status: :unprocessable_entity}
  		end
  	end
  end


  private

  	def note_params
  		params.require(:note).permit(:title, :body, :project_id)
  	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeDevelop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-mutate-approach="sync"></script>
    <script src="https://kit.fontawesome.com/75b0b3b76e.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" type="text/javascript"></script>
    <!-- <link href="toastr.css" rel="stylesheet"/>
    <script src="toastr.js"></script> -->
  </head>

  <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-inverse">
        <div class="d-flex flex-grow-1">
            <% if current_developer %>
              <a class="navbar-brand d-none d-lg-inline-block" href="/developers/dashboard"> weDevelop </a>
            <% elsif current_client %>
              <a class="navbar-brand d-none d-lg-inline-block" href="/clients/dashboard"> weDevelop </a>
            <% else %>
              <a class="navbar-brand d-none d-lg-inline-block" href="/"> weDevelop </a>
            <% end %>
            
            <div class="w-100 text-right">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
        <div class="collapse navbar-collapse flex-grow-1 text-right" id="nav-buttons">
            <ul class="navbar-nav ms-auto flex-nowrap">
              <% if current_developer %>
                <li>
                  <%= link_to "Dashboard", developers_dashboard_path, class: 'nav-link m-2 menu-item' %>
                </li>
                <li>
                  <%= link_to "My Account", edit_developer_registration_path, class: 'nav-link m-2 menu-item' %>
                </li>
                <li class="nav-item" >
                  <%= link_to "Sign Out", destroy_developer_session_path, method: :delete, class: 'nav-link m-2 menu-item' %>
                </li>
              <% elsif current_client %>
                <li>
                  <%= link_to "Dashboard", clients_dashboard_path, class: 'nav-link m-2 menu-item' %>
                </li>
                <li>
                  <%= link_to "My Account", edit_client_registration_path, class: 'nav-link m-2 menu-item' %>
                </li>
                <li class="nav-item">
                  <%= link_to "Sign Out", destroy_client_session_path, method: :delete, class: 'nav-link m-2 menu-item' %>
                </li>
              <% else %>
                <li class="nav-item">
                    <a href="/developers/sign_in" class="nav-link m-2 menu-item">Sign In as Developer</a>
                </li>
                <li class="nav-item">
                    <a href="/clients/sign_in" class="nav-link m-2 menu-item">Sign In as Client</a>
                </li>
              <% end %>
            </ul>
        </div>
    </nav>
  

    

    <div>
      
      <% unless flash.empty? %>
         <script type="text/javascript">
            <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
           toastr['<%= type %>']('<%= f[1] %>', '', {
                                                  "closeButton": true,
                                                  "positionClass": "toast-top-center", 
                                                  "onclick": null, 
                                                  "showDuration": "300", 
                                                  "hideDuration": "1000", 
                                                  "timeOut": "3000", 
                                                  "extendedTimeOut": "1000", 
                                                  "showEasing": "swing", 
                                                  "hideEasing": "linear", 
                                                  "showMethod": "fadeIn", 
                                                  "progressBar": true,
                                                  "hideMethod": "fadeOut"});
         <% end %>
         </script>
      <% end %>


    <%= yield %>
    </div>
 
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-fluid home-intro">
    <div class="container" id="test">
        <div class="jumbotron text-center">
            <h1 class="display-4">Hello, world!</h1>
              <p class="lead">Maintaining project organization while juggling all of your various clients just became much, much easier.</p>
              
              
              <a class="btn btn-primary btn-lg" href="/developers/sign_up" role="button">Sign Up as a developer today!</a>
          </div>
    </div>    
</div>




<div class="container py-5" id="business-points">
    <div class="row py-5">
        <div class="col-md-12 text-center">
            <h3 class="font-weight-bold">There are so many benefits to joining our platform! Here are a few:</h3>
        </div>
        <div class="row text-center">
            <div class="col-md-4">
                <img src="https://wedevelop.s3-us-west-2.amazonaws.com/round1.png" class="img-fluid rounded-circle">
                <h6 class="mb-3 mt-5">Message Your Clients</h6>
                <p class="mb-5 text-muted">Keep an open channel of communication flowing with your clients in a secure location that you both have access to.</p>
            </div>
            <div class="col-md-4">
                <img src="https://wedevelop.s3-us-west-2.amazonaws.com/round2.png" class="img-fluid rounded-circle">
                <h6 class="mb-3 mt-5">Finalize Agreements</h6>
                <p class="mb-5 text-muted">Allow the client to agree to new features or updates as the work progresses to prevent disagreements down the road.</p>
            </div>
            <div class="col-md-4">
                <img src="https://wedevelop.s3-us-west-2.amazonaws.com/round3.png" class="img-fluid rounded-circle">
                <h6 class="mb-3 mt-5">Share New Features</h6>
                <p class="mb-5 text-muted">Update your clients when new features to the project are added.</p>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-4">
                <img src="https://wedevelop.s3-us-west-2.amazonaws.com/round4.png" class="img-fluid rounded-circle">
                <h6 class="mb-3 mt-5">Track Open Items</h6>
                <p class="mb-5 text-muted">Transparently communicate the status of open items with your client and address them as your project progresses.</p>
            </div>
            <div class="col-md-4">
                <img src="https://wedevelop.s3-us-west-2.amazonaws.com/round5.png" class="img-fluid rounded-circle">
                <h6 class="mb-3 mt-5">Generate New Ideas</h6>
                <p class="mb-5 text-muted">Allow your clients to introduce new ideas, expand the scope of work, and increase your revenue potential as your project comes together.</p>
            </div>
            <div class="col-md-4">
                <img src="https://wedevelop.s3-us-west-2.amazonaws.com/round6.png" class="img-fluid rounded-circle">
                <h6 class="mb-3 mt-5">Collaborate on Your Project</h6>
                <p class="mb-5 text-muted">Allowing your client to view the project's status in real time will increase their trust in you and will help secure more contracts in the future. </p>
            </div>
        </div>
    </div>
</div>



<div class="container-fluid" id="filler-img">
    <div class="row text-center">
        <div class="col-md-12">
            <h1>Developers love using weDevelop!</h1>
        </div>
    </div>
</div>



<div class="container" id="reviews">
    <div class="row text-center">
        <div class="col-lg-4 col-md-12">
            <img src="https://wedevelop-dev.s3.amazonaws.com/matthew-hamilton-tNCH0sKSZbA-unsplash.jpg" class="img-fluid img-thumbnail rounded"></img>
            <h5 class="person-review-details mb-3 mt-5">Mehreen Zarei, Seattle WA</h5>
            <p class="mb-5">Using weDevelop with my clients has allowed me to put their minds at ease as their project comes together.  They are able to see that progress is being made and they know how to contact me if they have a concern.  This lets me spend more time working on the project and less time on the phone talking about it.</p>
        </div>
        <div class="col-lg-4 col-md-12">
            <img src="https://wedevelop.s3-us-west-2.amazonaws.com/cesar-rincon-XHVpWcr5grQ-unsplash.jpg" class="img-fluid img-thumbnail rounded"></img>
            <h5 class="person-review-details mb-3 mt-5">Allen Campbell, Chicago IL</h5>
            <p class="mb-5">When working with multiple clients on multiple projects it can be very easy to send a message to the wrong person.  With weDevelop, my clients are attached to the project that I'm working on so there is no possibly of mixing them up.  WeDevelop has saved me many awkward conversations with clients that didn't think I was giving them the time they deserved.</p>
        </div>
        <div class="col-lg-4 col-md-12">
            <img src="https://wedevelop-dev.s3.amazonaws.com/true-agency-JwP90y9wgr4-unsplash.jpg" class="img-fluid img-thumbnail rounded"></img>
            <h5 class="person-review-details mb-3 mt-5">Lily Anderson, San Francisco CA</h5>
            <p class="mb-5">Giving my clients the ability to watch their project come together and have their concerns heard has earned my repeated contracts with clients.  They are impressed with the professionalism that weDevelop gives my development team and I am able to use it as a selling point for future clients.  With weDevelop I have more contracts with happier clients than I ever have before.</p>
        </div>
    </div>
</div>